//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMCL.Main.Public.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YMCL.Main.Public.Langs.MainLang", typeof(MainLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账户错误 的本地化字符串。
        /// </summary>
        public static string AccountError {
            get {
                return ResourceManager.GetString("AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户名称不可为空 的本地化字符串。
        /// </summary>
        public static string AccountNameCannotBeNull {
            get {
                return ResourceManager.GetString("AccountNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户密码 的本地化字符串。
        /// </summary>
        public static string AccountPassword {
            get {
                return ResourceManager.GetString("AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活Windows/Office 的本地化字符串。
        /// </summary>
        public static string ActivateWinOffice {
            get {
                return ResourceManager.GetString("ActivateWinOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件夹 的本地化字符串。
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加音频文件 的本地化字符串。
        /// </summary>
        public static string AddLocalSong {
            get {
                return ResourceManager.GetString("AddLocalSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新账户 的本地化字符串。
        /// </summary>
        public static string AddNewAccount {
            get {
                return ResourceManager.GetString("AddNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有版本 的本地化字符串。
        /// </summary>
        public static string AllVersion {
            get {
                return ResourceManager.GetString("AllVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任意加载器 的本地化字符串。
        /// </summary>
        public static string AnyModLoader {
            get {
                return ResourceManager.GetString("AnyModLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有来源 的本地化字符串。
        /// </summary>
        public static string AnySource {
            get {
                return ResourceManager.GetString("AnySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动安装 的本地化字符串。
        /// </summary>
        public static string AutoInstall {
            get {
                return ResourceManager.GetString("AutoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动加入服务器 的本地化字符串。
        /// </summary>
        public static string AutoJoinServer {
            get {
                return ResourceManager.GetString("AutoJoinServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动扫描 的本地化字符串。
        /// </summary>
        public static string AutoScan {
            get {
                return ResourceManager.GetString("AutoScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载 的本地化字符串。
        /// </summary>
        public static string BeginDownload {
            get {
                return ResourceManager.GetString("BeginDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始安装 的本地化字符串。
        /// </summary>
        public static string BeginInstall {
            get {
                return ResourceManager.GetString("BeginInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 构建启动配置失败 的本地化字符串。
        /// </summary>
        public static string BuildLaunchConfigFail {
            get {
                return ResourceManager.GetString("BuildLaunchConfigFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消激活Windows 的本地化字符串。
        /// </summary>
        public static string CancelActivateWin {
            get {
                return ResourceManager.GetString("CancelActivateWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此操作会移除Windows激活状态，导致Windows个性化等功能不可用，是否继续？ 的本地化字符串。
        /// </summary>
        public static string CancelActivateWinTip {
            get {
                return ResourceManager.GetString("CancelActivateWinTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到合适Java 的本地化字符串。
        /// </summary>
        public static string CannotFandRightJava {
            get {
                return ResourceManager.GetString("CannotFandRightJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开浏览器 的本地化字符串。
        /// </summary>
        public static string CannotOpenBrowser {
            get {
                return ResourceManager.GetString("CannotOpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新失败 的本地化字符串。
        /// </summary>
        public static string CheckUpdateFail {
            get {
                return ResourceManager.GetString("CheckUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择平台 的本地化字符串。
        /// </summary>
        public static string ChooseArchitecture {
            get {
                return ResourceManager.GetString("ChooseArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色彩模式 的本地化字符串。
        /// </summary>
        public static string ColorMode {
            get {
                return ResourceManager.GetString("ColorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制代码并打开浏览器 的本地化字符串。
        /// </summary>
        public static string CopyCodeAndOPenBrowser {
            get {
                return ResourceManager.GetString("CopyCodeAndOPenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl + C 复制以下链接并粘贴至浏览器 的本地化字符串。
        /// </summary>
        public static string CopyUrlAndManualOpen {
            get {
                return ResourceManager.GetString("CopyUrlAndManualOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建游戏实例失败 的本地化字符串。
        /// </summary>
        public static string CreateGameEntryFail {
            get {
                return ResourceManager.GetString("CreateGameEntryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前是最新版本 的本地化字符串。
        /// </summary>
        public static string CurrentlyTheLatestVersion {
            get {
                return ResourceManager.GetString("CurrentlyTheLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义主页面 的本地化字符串。
        /// </summary>
        public static string CustomHomePage {
            get {
                return ResourceManager.GetString("CustomHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义主页面源代码错误 的本地化字符串。
        /// </summary>
        public static string CustomHomePageSourceCodeError {
            get {
                return ResourceManager.GetString("CustomHomePageSourceCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中项 的本地化字符串。
        /// </summary>
        public static string DeleteSelect {
            get {
                return ResourceManager.GetString("DeleteSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中项 的本地化字符串。
        /// </summary>
        public static string DelSeletedItem {
            get {
                return ResourceManager.GetString("DelSeletedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全不选 的本地化字符串。
        /// </summary>
        public static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用选中项 的本地化字符串。
        /// </summary>
        public static string DisableSelect {
            get {
                return ResourceManager.GetString("DisableSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败 的本地化字符串。
        /// </summary>
        public static string DownloadFail {
            get {
                return ResourceManager.GetString("DownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        public static string DownloadFinish {
            get {
                return ResourceManager.GetString("DownloadFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱地址 的本地化字符串。
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用独立核心 的本地化字符串。
        /// </summary>
        public static string EnableIndependencyCore {
            get {
                return ResourceManager.GetString("EnableIndependencyCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用选中项 的本地化字符串。
        /// </summary>
        public static string EnableSelect {
            get {
                return ResourceManager.GetString("EnableSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用Api时出错 的本地化字符串。
        /// </summary>
        public static string ErrorCallingApi {
            get {
                return ResourceManager.GetString("ErrorCallingApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        public static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件选择窗口 的本地化字符串。
        /// </summary>
        public static string FileSelectWindow {
            get {
                return ResourceManager.GetString("FileSelectWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹已存在 的本地化字符串。
        /// </summary>
        public static string FolderAlreadyExists {
            get {
                return ResourceManager.GetString("FolderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹不存在 的本地化字符串。
        /// </summary>
        public static string FolderNotExist {
            get {
                return ResourceManager.GetString("FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        public static string FollowSystem {
            get {
                return ResourceManager.GetString("FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本 的本地化字符串。
        /// </summary>
        public static string FoundNewVersion {
            get {
                return ResourceManager.GetString("FoundNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏已退出 的本地化字符串。
        /// </summary>
        public static string GameExited {
            get {
                return ResourceManager.GetString("GameExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏版本 的本地化字符串。
        /// </summary>
        public static string GameVersion {
            get {
                return ResourceManager.GetString("GameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生异常 的本地化字符串。
        /// </summary>
        public static string GetException {
            get {
                return ResourceManager.GetString("GetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取失败 的本地化字符串。
        /// </summary>
        public static string GetFail {
            get {
                return ResourceManager.GetString("GetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取可安装列表失败 的本地化字符串。
        /// </summary>
        public static string GetInstallableVersionFail {
            get {
                return ResourceManager.GetString("GetInstallableVersionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取更新统一资源定位器 的本地化字符串。
        /// </summary>
        public static string GetUpdateUrl {
            get {
                return ResourceManager.GetString("GetUpdateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL 以 Apache License 协议开放源代码，可以修改且分发，但软件必须包含原始代码的版权声明和许可声明，以及一个包含许可信息的通知文件。 的本地化字符串。
        /// </summary>
        public static string GPL3Text {
            get {
                return ResourceManager.GetString("GPL3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含特殊字符 的本地化字符串。
        /// </summary>
        public static string IncludeSpecialWord {
            get {
                return ResourceManager.GetString("IncludeSpecialWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化音频库失败 的本地化字符串。
        /// </summary>
        public static string InitAudioLibraryFail {
            get {
                return ResourceManager.GetString("InitAudioLibraryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入账户名称 的本地化字符串。
        /// </summary>
        public static string InputAccountName {
            get {
                return ResourceManager.GetString("InputAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入文件路径 的本地化字符串。
        /// </summary>
        public static string InputFilePath {
            get {
                return ResourceManager.GetString("InputFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入文件夹路径 的本地化字符串。
        /// </summary>
        public static string InputFolderPath {
            get {
                return ResourceManager.GetString("InputFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装 的本地化字符串。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装失败 的本地化字符串。
        /// </summary>
        public static string InstallFail {
            get {
                return ResourceManager.GetString("InstallFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装完成 的本地化字符串。
        /// </summary>
        public static string InstallFinish {
            get {
                return ResourceManager.GetString("InstallFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装预览 的本地化字符串。
        /// </summary>
        public static string InstallPreview {
            get {
                return ResourceManager.GetString("InstallPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试执行：
        ///
        ///sudo apt install libvlc-dev
        ///sudo apt install vlc 的本地化字符串。
        /// </summary>
        public static string InstallVlcTip {
            get {
                return ResourceManager.GetString("InstallVlcTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新版本 的本地化字符串。
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动失败 的本地化字符串。
        /// </summary>
        public static string LaunchFail {
            get {
                return ResourceManager.GetString("LaunchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动完成 的本地化字符串。
        /// </summary>
        public static string LaunchFinish {
            get {
                return ResourceManager.GetString("LaunchFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        public static string LaunchGame {
            get {
                return ResourceManager.GetString("LaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动进度 的本地化字符串。
        /// </summary>
        public static string LaunchProgress {
            get {
                return ResourceManager.GetString("LaunchProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让YMCL选择合适的Java 的本地化字符串。
        /// </summary>
        public static string LetYMCLChooseJava {
            get {
                return ResourceManager.GetString("LetYMCLChooseJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中... 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载更多 的本地化字符串。
        /// </summary>
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地源代码 的本地化字符串。
        /// </summary>
        public static string LocalSourceCode {
            get {
                return ResourceManager.GetString("LocalSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动添加 的本地化字符串。
        /// </summary>
        public static string ManualAdd {
            get {
                return ResourceManager.GetString("ManualAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动输入 的本地化字符串。
        /// </summary>
        public static string ManualInput {
            get {
                return ResourceManager.GetString("ManualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动打开 的本地化字符串。
        /// </summary>
        public static string ManualOpen {
            get {
                return ResourceManager.GetString("ManualOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配的版本 的本地化字符串。
        /// </summary>
        public static string MatchingVersion {
            get {
                return ResourceManager.GetString("MatchingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大内存 的本地化字符串。
        /// </summary>
        public static string MaxMem {
            get {
                return ResourceManager.GetString("MaxMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微软登录 的本地化字符串。
        /// </summary>
        public static string MicrosoftLogin {
            get {
                return ResourceManager.GetString("MicrosoftLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft文件夹 的本地化字符串。
        /// </summary>
        public static string MinecraftFolder {
            get {
                return ResourceManager.GetString("MinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecrat发生崩溃 的本地化字符串。
        /// </summary>
        public static string MineratCrashed {
            get {
                return ResourceManager.GetString("MineratCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组 的本地化字符串。
        /// </summary>
        public static string Mod {
            get {
                return ResourceManager.GetString("Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组名称 的本地化字符串。
        /// </summary>
        public static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组文件夹 的本地化字符串。
        /// </summary>
        public static string ModsFolder {
            get {
                return ResourceManager.GetString("ModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到回收站 的本地化字符串。
        /// </summary>
        public static string MoveToRecycleBin {
            get {
                return ResourceManager.GetString("MoveToRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  账户 的本地化字符串。
        /// </summary>
        public static string NavAccount {
            get {
                return ResourceManager.GetString("NavAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  下载 的本地化字符串。
        /// </summary>
        public static string NavDownload {
            get {
                return ResourceManager.GetString("NavDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  启动 的本地化字符串。
        /// </summary>
        public static string NavLaunch {
            get {
                return ResourceManager.GetString("NavLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  启动器 的本地化字符串。
        /// </summary>
        public static string NavLauncher {
            get {
                return ResourceManager.GetString("NavLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  更多 的本地化字符串。
        /// </summary>
        public static string NavMore {
            get {
                return ResourceManager.GetString("NavMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  音乐 的本地化字符串。
        /// </summary>
        public static string NavMusic {
            get {
                return ResourceManager.GetString("NavMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  个性化 的本地化字符串。
        /// </summary>
        public static string NavPersonalize {
            get {
                return ResourceManager.GetString("NavPersonalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  设置 的本地化字符串。
        /// </summary>
        public static string NavSetting {
            get {
                return ResourceManager.GetString("NavSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需选择&apos;.minecraft&apos;文件夹 的本地化字符串。
        /// </summary>
        public static string NeedToSelectMinecraftFolder {
            get {
                return ResourceManager.GetString("NeedToSelectMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无附加安装 的本地化字符串。
        /// </summary>
        public static string NoAdditionalInstall {
            get {
                return ResourceManager.GetString("NoAdditionalInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无可用项目 的本地化字符串。
        /// </summary>
        public static string NoAvailableItem {
            get {
                return ResourceManager.GetString("NoAvailableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择游戏 的本地化字符串。
        /// </summary>
        public static string NoChooseGame {
            get {
                return ResourceManager.GetString("NoChooseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择游戏或无法找到游戏 的本地化字符串。
        /// </summary>
        public static string NoChooseGameOrCannotFindGame {
            get {
                return ResourceManager.GetString("NoChooseGameOrCannotFindGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线登录 的本地化字符串。
        /// </summary>
        public static string OfflineLogin {
            get {
                return ResourceManager.GetString("OfflineLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远古版本 的本地化字符串。
        /// </summary>
        public static string OldVersion {
            get {
                return ResourceManager.GetString("OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启 的本地化字符串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件方式 的本地化字符串。
        /// </summary>
        public static string OpenFileWay {
            get {
                return ResourceManager.GetString("OpenFileWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开源项目使用表 的本地化字符串。
        /// </summary>
        public static string OpenSourceProjectUsageTable {
            get {
                return ResourceManager.GetString("OpenSourceProjectUsageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 概览 的本地化字符串。
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放列表 的本地化字符串。
        /// </summary>
        public static string PlayList {
            get {
                return ResourceManager.GetString("PlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览版本 的本地化字符串。
        /// </summary>
        public static string PreviewVersion {
            get {
                return ResourceManager.GetString("PreviewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正式版本 的本地化字符串。
        /// </summary>
        public static string ReleaseVersion {
            get {
                return ResourceManager.GetString("ReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新加载 的本地化字符串。
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复的项目 的本地化字符串。
        /// </summary>
        public static string RepeatItem {
            get {
                return ResourceManager.GetString("RepeatItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源包文件夹 的本地化字符串。
        /// </summary>
        public static string ResourcepacksFolder {
            get {
                return ResourceManager.GetString("ResourcepacksFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ← 返回 的本地化字符串。
        /// </summary>
        public static string ReturnWithIcon {
            get {
                return ResourceManager.GetString("ReturnWithIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行激活 的本地化字符串。
        /// </summary>
        public static string RunActivate {
            get {
                return ResourceManager.GetString("RunActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行命令失败 的本地化字符串。
        /// </summary>
        public static string RunCommandFail {
            get {
                return ResourceManager.GetString("RunCommandFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件 的本地化字符串。
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档文件夹 的本地化字符串。
        /// </summary>
        public static string SavesFolder {
            get {
                return ResourceManager.GetString("SavesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描Java成功 的本地化字符串。
        /// </summary>
        public static string ScanJavaSuccess {
            get {
                return ResourceManager.GetString("ScanJavaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索关键词... 的本地化字符串。
        /// </summary>
        public static string SearchKeyword {
            get {
                return ResourceManager.GetString("SearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索无结果 的本地化字符串。
        /// </summary>
        public static string SearchNoResult {
            get {
                return ResourceManager.GetString("SearchNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择账户类型 的本地化字符串。
        /// </summary>
        public static string SelectAccountType {
            get {
                return ResourceManager.GetString("SelectAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选择项目： 的本地化字符串。
        /// </summary>
        public static string SelectedItem {
            get {
                return ResourceManager.GetString("SelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择Java 的本地化字符串。
        /// </summary>
        public static string SelectJava {
            get {
                return ResourceManager.GetString("SelectJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择&apos;.minecraft&apos;文件夹 的本地化字符串。
        /// </summary>
        public static string SelectMinecraftFolder {
            get {
                return ResourceManager.GetString("SelectMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择音频文件 的本地化字符串。
        /// </summary>
        public static string SelectMusicFile {
            get {
                return ResourceManager.GetString("SelectMusicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光影包文件夹 的本地化字符串。
        /// </summary>
        public static string ShaderpacksFolder {
            get {
                return ResourceManager.GetString("ShaderpacksFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示游戏输出 的本地化字符串。
        /// </summary>
        public static string ShowGameOutput {
            get {
                return ResourceManager.GetString("ShowGameOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功 的本地化字符串。
        /// </summary>
        public static string SuccessAdd {
            get {
                return ResourceManager.GetString("SuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除成功 的本地化字符串。
        /// </summary>
        public static string SuccessRemove {
            get {
                return ResourceManager.GetString("SuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在此项目 的本地化字符串。
        /// </summary>
        public static string TheItemAlreadyExist {
            get {
                return ResourceManager.GetString("TheItemAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Java不正确 的本地化字符串。
        /// </summary>
        public static string TheJavaIsError {
            get {
                return ResourceManager.GetString("TheJavaIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题色 的本地化字符串。
        /// </summary>
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本名称将被重命名为： 的本地化字符串。
        /// </summary>
        public static string TheVersionNameWillBeRenamedTo {
            get {
                return ResourceManager.GetString("TheVersionNameWillBeRenamedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第三方登录 的本地化字符串。
        /// </summary>
        public static string ThirdPartyLogin {
            get {
                return ResourceManager.GetString("ThirdPartyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此平台不支持自动更新，打开以下路径手动替换 的本地化字符串。
        /// </summary>
        public static string ThisArchitectureCannotAutoUpdate {
            get {
                return ResourceManager.GetString("ThisArchitectureCannotAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此功能正在开发中 的本地化字符串。
        /// </summary>
        public static string ThisFeatureIsCurrentlyUnderDevelopment {
            get {
                return ResourceManager.GetString("ThisFeatureIsCurrentlyUnderDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该功能仅支持Windows10以上，低于此版本系统不保证激活成功 的本地化字符串。
        /// </summary>
        public static string ThisFeatureOnlySupportsWindows10AndAbove {
            get {
                return ResourceManager.GetString("ThisFeatureOnlySupportsWindows10AndAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该功能仅支持Windows平台 的本地化字符串。
        /// </summary>
        public static string ThisFeatureOnlySupportsWindowsPlatform {
            get {
                return ResourceManager.GetString("ThisFeatureOnlySupportsWindowsPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百宝箱 的本地化字符串。
        /// </summary>
        public static string TreasureBox {
            get {
                return ResourceManager.GetString("TreasureBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未处理的异常 的本地化字符串。
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败 的本地化字符串。
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用全局设置 的本地化字符串。
        /// </summary>
        public static string UseGlobalSetting {
            get {
                return ResourceManager.GetString("UseGlobalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户数据文件夹 的本地化字符串。
        /// </summary>
        public static string UserDataFolder {
            get {
                return ResourceManager.GetString("UserDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证代码 的本地化字符串。
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证服务器 的本地化字符串。
        /// </summary>
        public static string VerificationServer {
            get {
                return ResourceManager.GetString("VerificationServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证账户 的本地化字符串。
        /// </summary>
        public static string VerifyingAccount {
            get {
                return ResourceManager.GetString("VerifyingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本文件夹 的本地化字符串。
        /// </summary>
        public static string VersionFolder {
            get {
                return ResourceManager.GetString("VersionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本列表 的本地化字符串。
        /// </summary>
        public static string VersionList {
            get {
                return ResourceManager.GetString("VersionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本设置 的本地化字符串。
        /// </summary>
        public static string VersionSetting {
            get {
                return ResourceManager.GetString("VersionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看更新内容 的本地化字符串。
        /// </summary>
        public static string ViewUpdatedContent {
            get {
                return ResourceManager.GetString("ViewUpdatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待游戏窗口出现 的本地化字符串。
        /// </summary>
        public static string WaitForGameWindowAppear {
            get {
                return ResourceManager.GetString("WaitForGameWindowAppear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在等待微软账户验证完成
        ///跳转至浏览器完成验证 的本地化字符串。
        /// </summary>
        public static string WaitForMicrosoftVerification {
            get {
                return ResourceManager.GetString("WaitForMicrosoftVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口标题栏样式 的本地化字符串。
        /// </summary>
        public static string WindowTitleBarStyle {
            get {
                return ResourceManager.GetString("WindowTitleBarStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱不可为空 的本地化字符串。
        /// </summary>
        public static string YggdrasilEmailIsEmpty {
            get {
                return ResourceManager.GetString("YggdrasilEmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不可为空 的本地化字符串。
        /// </summary>
        public static string YggdrasilPasswordIsEmpty {
            get {
                return ResourceManager.GetString("YggdrasilPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证服务器不可为空 的本地化字符串。
        /// </summary>
        public static string YggdrasilServerUrlIsEmpty {
            get {
                return ResourceManager.GetString("YggdrasilServerUrlIsEmpty", resourceCulture);
            }
        }
    }
}
