//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMCL.Main.Public.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YMCL.Main.Public.Langs.MainLang", typeof(MainLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户错误.
        /// </summary>
        public static string AccountError {
            get {
                return ResourceManager.GetString("AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户名称不可为空.
        /// </summary>
        public static string AccountNameCannotBeNull {
            get {
                return ResourceManager.GetString("AccountNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户密码.
        /// </summary>
        public static string AccountPassword {
            get {
                return ResourceManager.GetString("AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 激活Windows/Office.
        /// </summary>
        public static string ActivateWinOffice {
            get {
                return ResourceManager.GetString("ActivateWinOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加文件夹.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加音频文件.
        /// </summary>
        public static string AddLocalSong {
            get {
                return ResourceManager.GetString("AddLocalSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加新账户.
        /// </summary>
        public static string AddNewAccount {
            get {
                return ResourceManager.GetString("AddNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将以下文件作为模组添加至当前版本.
        /// </summary>
        public static string AddTheFollowingFilesAsModsToTheCurrentVersion {
            get {
                return ResourceManager.GetString("AddTheFollowingFilesAsModsToTheCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有类型.
        /// </summary>
        public static string AllType {
            get {
                return ResourceManager.GetString("AllType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有版本.
        /// </summary>
        public static string AllVersion {
            get {
                return ResourceManager.GetString("AllVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任意加载器.
        /// </summary>
        public static string AnyModLoader {
            get {
                return ResourceManager.GetString("AnyModLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有来源.
        /// </summary>
        public static string AnySource {
            get {
                return ResourceManager.GetString("AnySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动安装.
        /// </summary>
        public static string AutoInstall {
            get {
                return ResourceManager.GetString("AutoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动加入服务器.
        /// </summary>
        public static string AutoJoinServer {
            get {
                return ResourceManager.GetString("AutoJoinServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动扫描.
        /// </summary>
        public static string AutoScan {
            get {
                return ResourceManager.GetString("AutoScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基岩版.
        /// </summary>
        public static string BedRockVersion {
            get {
                return ResourceManager.GetString("BedRockVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始下载.
        /// </summary>
        public static string BeginDownload {
            get {
                return ResourceManager.GetString("BeginDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始安装.
        /// </summary>
        public static string BeginInstall {
            get {
                return ResourceManager.GetString("BeginInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 构建启动配置失败.
        /// </summary>
        public static string BuildLaunchConfigFail {
            get {
                return ResourceManager.GetString("BuildLaunchConfigFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消激活Windows.
        /// </summary>
        public static string CancelActivateWin {
            get {
                return ResourceManager.GetString("CancelActivateWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此操作会移除Windows激活状态，导致Windows个性化等功能不可用，是否继续？.
        /// </summary>
        public static string CancelActivateWinTip {
            get {
                return ResourceManager.GetString("CancelActivateWinTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法找到合适Java.
        /// </summary>
        public static string CannotFandRightJava {
            get {
                return ResourceManager.GetString("CannotFandRightJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法打开基岩版设置.
        /// </summary>
        public static string CannotOpenBedRockSetting {
            get {
                return ResourceManager.GetString("CannotOpenBedRockSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法打开浏览器.
        /// </summary>
        public static string CannotOpenBrowser {
            get {
                return ResourceManager.GetString("CannotOpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新失败.
        /// </summary>
        public static string CheckUpdateFail {
            get {
                return ResourceManager.GetString("CheckUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择平台.
        /// </summary>
        public static string ChooseArchitecture {
            get {
                return ResourceManager.GetString("ChooseArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择语言/Choose Language.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 色彩模式.
        /// </summary>
        public static string ColorMode {
            get {
                return ResourceManager.GetString("ColorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制代码并打开浏览器.
        /// </summary>
        public static string CopyCodeAndOPenBrowser {
            get {
                return ResourceManager.GetString("CopyCodeAndOPenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + C 复制以下链接并粘贴至浏览器.
        /// </summary>
        public static string CopyUrlAndManualOpen {
            get {
                return ResourceManager.GetString("CopyUrlAndManualOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建游戏实例失败.
        /// </summary>
        public static string CreateGameEntryFail {
            get {
                return ResourceManager.GetString("CreateGameEntryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前是最新版本.
        /// </summary>
        public static string CurrentlyTheLatestVersion {
            get {
                return ResourceManager.GetString("CurrentlyTheLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义背景图.
        /// </summary>
        public static string CustomBackGroundImg {
            get {
                return ResourceManager.GetString("CustomBackGroundImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义主页面.
        /// </summary>
        public static string CustomHomePage {
            get {
                return ResourceManager.GetString("CustomHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义主页面源代码错误.
        /// </summary>
        public static string CustomHomePageSourceCodeError {
            get {
                return ResourceManager.GetString("CustomHomePageSourceCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中项.
        /// </summary>
        public static string DeleteSelect {
            get {
                return ResourceManager.GetString("DeleteSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中项.
        /// </summary>
        public static string DelSeletedItem {
            get {
                return ResourceManager.GetString("DelSeletedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全不选.
        /// </summary>
        public static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用所有.
        /// </summary>
        public static string DisableAll {
            get {
                return ResourceManager.GetString("DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用选中项.
        /// </summary>
        public static string DisableSelect {
            get {
                return ResourceManager.GetString("DisableSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载失败.
        /// </summary>
        public static string DownloadFail {
            get {
                return ResourceManager.GetString("DownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新下载失败文件.
        /// </summary>
        public static string DownloadFailedFileAgain {
            get {
                return ResourceManager.GetString("DownloadFailedFileAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载完成.
        /// </summary>
        public static string DownloadFinish {
            get {
                return ResourceManager.GetString("DownloadFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载整合包模组.
        /// </summary>
        public static string DownloadModPackMod {
            get {
                return ResourceManager.GetString("DownloadModPackMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载成功.
        /// </summary>
        public static string DownloadSuccess {
            get {
                return ResourceManager.GetString("DownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱地址.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用所有.
        /// </summary>
        public static string EnableAll {
            get {
                return ResourceManager.GetString("EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用独立核心.
        /// </summary>
        public static string EnableIndependencyCore {
            get {
                return ResourceManager.GetString("EnableIndependencyCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用选中项.
        /// </summary>
        public static string EnableSelect {
            get {
                return ResourceManager.GetString("EnableSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调用Api时出错.
        /// </summary>
        public static string ErrorCallingApi {
            get {
                return ResourceManager.GetString("ErrorCallingApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件不存在.
        /// </summary>
        public static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件选择窗口.
        /// </summary>
        public static string FileSelectWindow {
            get {
                return ResourceManager.GetString("FileSelectWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解压整合包完成.
        /// </summary>
        public static string FinsihUnzipModPack {
            get {
                return ResourceManager.GetString("FinsihUnzipModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件夹已存在.
        /// </summary>
        public static string FolderAlreadyExists {
            get {
                return ResourceManager.GetString("FolderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件夹不存在.
        /// </summary>
        public static string FolderNotExist {
            get {
                return ResourceManager.GetString("FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string FollowSystem {
            get {
                return ResourceManager.GetString("FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现新版本.
        /// </summary>
        public static string FoundNewVersion {
            get {
                return ResourceManager.GetString("FoundNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏已退出.
        /// </summary>
        public static string GameExited {
            get {
                return ResourceManager.GetString("GameExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏版本.
        /// </summary>
        public static string GameVersion {
            get {
                return ResourceManager.GetString("GameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发生异常.
        /// </summary>
        public static string GetException {
            get {
                return ResourceManager.GetString("GetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取失败.
        /// </summary>
        public static string GetFail {
            get {
                return ResourceManager.GetString("GetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取可安装列表失败.
        /// </summary>
        public static string GetInstallableVersionFail {
            get {
                return ResourceManager.GetString("GetInstallableVersionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取整合包信息.
        /// </summary>
        public static string GetModPackInfo {
            get {
                return ResourceManager.GetString("GetModPackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取更新统一资源定位器.
        /// </summary>
        public static string GetUpdateUrl {
            get {
                return ResourceManager.GetString("GetUpdateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YMCL 以 Apache License 协议开放源代码，可以修改且分发，但软件必须包含原始代码的版权声明和许可声明，以及一个包含许可信息的通知文件。.
        /// </summary>
        public static string GPL3Text {
            get {
                return ResourceManager.GetString("GPL3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如未安装基岩版则无法启动.
        /// </summary>
        public static string IfInstallBedRock {
            get {
                return ResourceManager.GetString("IfInstallBedRock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入失败.
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入成功.
        /// </summary>
        public static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包含特殊字符.
        /// </summary>
        public static string IncludeSpecialWord {
            get {
                return ResourceManager.GetString("IncludeSpecialWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化音频库失败.
        /// </summary>
        public static string InitAudioLibraryFail {
            get {
                return ResourceManager.GetString("InitAudioLibraryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入账户名称.
        /// </summary>
        public static string InputAccountName {
            get {
                return ResourceManager.GetString("InputAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入文件路径.
        /// </summary>
        public static string InputFilePath {
            get {
                return ResourceManager.GetString("InputFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入文件夹路径.
        /// </summary>
        public static string InputFolderPath {
            get {
                return ResourceManager.GetString("InputFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入皮肤文件路径.
        /// </summary>
        public static string InputSkinFilePath {
            get {
                return ResourceManager.GetString("InputSkinFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装失败.
        /// </summary>
        public static string InstallFail {
            get {
                return ResourceManager.GetString("InstallFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装完成.
        /// </summary>
        public static string InstallFinish {
            get {
                return ResourceManager.GetString("InstallFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装预览.
        /// </summary>
        public static string InstallPreview {
            get {
                return ResourceManager.GetString("InstallPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将以下文件作为整合包(CurseForge格式)安装.
        /// </summary>
        public static string InstallTheFollowingFilesAsAnIntegrationPackageCurseforgeFormat {
            get {
                return ResourceManager.GetString("InstallTheFollowingFilesAsAnIntegrationPackageCurseforgeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尝试执行: 
        ///
        ///sudo apt install libvlc-dev
        ///sudo apt install vlc.
        /// </summary>
        public static string InstallVlcTip {
            get {
                return ResourceManager.GetString("InstallVlcTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string ja_JP {
            get {
                return ResourceManager.GetString("ja_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新版本.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动失败.
        /// </summary>
        public static string LaunchFail {
            get {
                return ResourceManager.GetString("LaunchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动完成.
        /// </summary>
        public static string LaunchFinish {
            get {
                return ResourceManager.GetString("LaunchFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动游戏.
        /// </summary>
        public static string LaunchGame {
            get {
                return ResourceManager.GetString("LaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动进度.
        /// </summary>
        public static string LaunchProgress {
            get {
                return ResourceManager.GetString("LaunchProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 让YMCL选择合适的Java.
        /// </summary>
        public static string LetYMCLChooseJava {
            get {
                return ResourceManager.GetString("LetYMCLChooseJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载中....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载更多.
        /// </summary>
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地源代码.
        /// </summary>
        public static string LocalSourceCode {
            get {
                return ResourceManager.GetString("LocalSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录失败.
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动添加.
        /// </summary>
        public static string ManualAdd {
            get {
                return ResourceManager.GetString("ManualAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动输入.
        /// </summary>
        public static string ManualInput {
            get {
                return ResourceManager.GetString("ManualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动打开.
        /// </summary>
        public static string ManualOpen {
            get {
                return ResourceManager.GetString("ManualOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地图.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匹配的版本.
        /// </summary>
        public static string MatchingVersion {
            get {
                return ResourceManager.GetString("MatchingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 材质包.
        /// </summary>
        public static string MaterialPack {
            get {
                return ResourceManager.GetString("MaterialPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大内存.
        /// </summary>
        public static string MaxMem {
            get {
                return ResourceManager.GetString("MaxMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微软登录.
        /// </summary>
        public static string MicrosoftLogin {
            get {
                return ResourceManager.GetString("MicrosoftLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft文件夹.
        /// </summary>
        public static string MinecraftFolder {
            get {
                return ResourceManager.GetString("MinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecrat发生崩溃.
        /// </summary>
        public static string MineratCrashed {
            get {
                return ResourceManager.GetString("MineratCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组.
        /// </summary>
        public static string Mod {
            get {
                return ResourceManager.GetString("Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改失败.
        /// </summary>
        public static string ModifyFail {
            get {
                return ResourceManager.GetString("ModifyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改皮肤(微软).
        /// </summary>
        public static string ModifyMicrosoftSkin {
            get {
                return ResourceManager.GetString("ModifyMicrosoftSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改成功.
        /// </summary>
        public static string ModifySuccess {
            get {
                return ResourceManager.GetString("ModifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组名称.
        /// </summary>
        public static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整合包信息.
        /// </summary>
        public static string ModPackInfo {
            get {
                return ResourceManager.GetString("ModPackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组文件夹.
        /// </summary>
        public static string ModsFolder {
            get {
                return ResourceManager.GetString("ModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动到回收站.
        /// </summary>
        public static string MoveToRecycleBin {
            get {
                return ResourceManager.GetString("MoveToRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音乐获取失败.
        /// </summary>
        public static string MusicGetFail {
            get {
                return ResourceManager.GetString("MusicGetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音乐不可用.
        /// </summary>
        public static string MusicNotAvailable {
            get {
                return ResourceManager.GetString("MusicNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  账户.
        /// </summary>
        public static string NavAccount {
            get {
                return ResourceManager.GetString("NavAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  下载.
        /// </summary>
        public static string NavDownload {
            get {
                return ResourceManager.GetString("NavDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  启动.
        /// </summary>
        public static string NavLaunch {
            get {
                return ResourceManager.GetString("NavLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  启动器.
        /// </summary>
        public static string NavLauncher {
            get {
                return ResourceManager.GetString("NavLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  更多.
        /// </summary>
        public static string NavMore {
            get {
                return ResourceManager.GetString("NavMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  音乐.
        /// </summary>
        public static string NavMusic {
            get {
                return ResourceManager.GetString("NavMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  个性化.
        /// </summary>
        public static string NavPersonalize {
            get {
                return ResourceManager.GetString("NavPersonalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  设置.
        /// </summary>
        public static string NavSetting {
            get {
                return ResourceManager.GetString("NavSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  任务.
        /// </summary>
        public static string NavTask {
            get {
                return ResourceManager.GetString("NavTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要重启YMCL.
        /// </summary>
        public static string NeedRestartApp {
            get {
                return ResourceManager.GetString("NeedRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需选择&apos;.minecraft&apos;文件夹.
        /// </summary>
        public static string NeedToSelectMinecraftFolder {
            get {
                return ResourceManager.GetString("NeedToSelectMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无附加安装.
        /// </summary>
        public static string NoAdditionalInstall {
            get {
                return ResourceManager.GetString("NoAdditionalInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无可用项目.
        /// </summary>
        public static string NoAvailableItem {
            get {
                return ResourceManager.GetString("NoAvailableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未选择游戏.
        /// </summary>
        public static string NoChooseGame {
            get {
                return ResourceManager.GetString("NoChooseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未选择游戏或无法找到游戏.
        /// </summary>
        public static string NoChooseGameOrCannotFindGame {
            get {
                return ResourceManager.GetString("NoChooseGameOrCannotFindGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无崩溃信息.
        /// </summary>
        public static string NoCrashInfo {
            get {
                return ResourceManager.GetString("NoCrashInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离线登录.
        /// </summary>
        public static string OfflineLogin {
            get {
                return ResourceManager.GetString("OfflineLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 远古版本.
        /// </summary>
        public static string OldVersion {
            get {
                return ResourceManager.GetString("OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅支持 Windows 10 以上系统.
        /// </summary>
        public static string OnlySupportsWindows10AndAboveSystems {
            get {
                return ResourceManager.GetString("OnlySupportsWindows10AndAboveSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件方式.
        /// </summary>
        public static string OpenFileWay {
            get {
                return ResourceManager.GetString("OpenFileWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件夹.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开源项目使用表.
        /// </summary>
        public static string OpenSourceProjectUsageTable {
            get {
                return ResourceManager.GetString("OpenSourceProjectUsageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 覆盖整合包.
        /// </summary>
        public static string OverrideModPack {
            get {
                return ResourceManager.GetString("OverrideModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 概览.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 播放列表.
        /// </summary>
        public static string PlayList {
            get {
                return ResourceManager.GetString("PlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件.
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览版本.
        /// </summary>
        public static string PreviewVersion {
            get {
                return ResourceManager.GetString("PreviewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新皮肤(微软).
        /// </summary>
        public static string RefreshMicrosoftSkin {
            get {
                return ResourceManager.GetString("RefreshMicrosoftSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 释放鼠标让YMCL处理此文件.
        /// </summary>
        public static string ReleaseTheMouseAndLetYmclProcessThisFile {
            get {
                return ResourceManager.GetString("ReleaseTheMouseAndLetYmclProcessThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正式版本.
        /// </summary>
        public static string ReleaseVersion {
            get {
                return ResourceManager.GetString("ReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新加载.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复的项目.
        /// </summary>
        public static string RepeatItem {
            get {
                return ResourceManager.GetString("RepeatItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源包文件夹.
        /// </summary>
        public static string ResourcepacksFolder {
            get {
                return ResourceManager.GetString("ResourcepacksFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← 返回.
        /// </summary>
        public static string ReturnWithIcon {
            get {
                return ResourceManager.GetString("ReturnWithIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский язык.
        /// </summary>
        public static string ru_RU {
            get {
                return ResourceManager.GetString("ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行激活.
        /// </summary>
        public static string RunActivate {
            get {
                return ResourceManager.GetString("RunActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行命令失败.
        /// </summary>
        public static string RunCommandFail {
            get {
                return ResourceManager.GetString("RunCommandFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存文件.
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存档文件夹.
        /// </summary>
        public static string SavesFolder {
            get {
                return ResourceManager.GetString("SavesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描Java成功.
        /// </summary>
        public static string ScanJavaSuccess {
            get {
                return ResourceManager.GetString("ScanJavaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索关键词....
        /// </summary>
        public static string SearchKeyword {
            get {
                return ResourceManager.GetString("SearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索无结果.
        /// </summary>
        public static string SearchNoResult {
            get {
                return ResourceManager.GetString("SearchNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择账户类型.
        /// </summary>
        public static string SelectAccountType {
            get {
                return ResourceManager.GetString("SelectAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择项目: .
        /// </summary>
        public static string SelectedItem {
            get {
                return ResourceManager.GetString("SelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择图像文件.
        /// </summary>
        public static string SelectImgFile {
            get {
                return ResourceManager.GetString("SelectImgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择Java.
        /// </summary>
        public static string SelectJava {
            get {
                return ResourceManager.GetString("SelectJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择&apos;.minecraft&apos;文件夹.
        /// </summary>
        public static string SelectMinecraftFolder {
            get {
                return ResourceManager.GetString("SelectMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择音频文件.
        /// </summary>
        public static string SelectMusicFile {
            get {
                return ResourceManager.GetString("SelectMusicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择皮肤文件.
        /// </summary>
        public static string SelectSkinFile {
            get {
                return ResourceManager.GetString("SelectSkinFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 光影包文件夹.
        /// </summary>
        public static string ShaderpacksFolder {
            get {
                return ResourceManager.GetString("ShaderpacksFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示游戏输出.
        /// </summary>
        public static string ShowGameOutput {
            get {
                return ResourceManager.GetString("ShowGameOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 皮肤模型.
        /// </summary>
        public static string SkinModel {
            get {
                return ResourceManager.GetString("SkinModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加成功.
        /// </summary>
        public static string SuccessAdd {
            get {
                return ResourceManager.GetString("SuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除成功.
        /// </summary>
        public static string SuccessRemove {
            get {
                return ResourceManager.GetString("SuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务中心.
        /// </summary>
        public static string TaskCenter {
            get {
                return ResourceManager.GetString("TaskCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已存在此项目.
        /// </summary>
        public static string TheItemAlreadyExist {
            get {
                return ResourceManager.GetString("TheItemAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java不正确.
        /// </summary>
        public static string TheJavaIsError {
            get {
                return ResourceManager.GetString("TheJavaIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题色.
        /// </summary>
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本名称将被重命名为: .
        /// </summary>
        public static string TheVersionNameWillBeRenamedTo {
            get {
                return ResourceManager.GetString("TheVersionNameWillBeRenamedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第三方登录.
        /// </summary>
        public static string ThirdPartyLogin {
            get {
                return ResourceManager.GetString("ThirdPartyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此平台不支持自动更新，打开以下路径手动替换.
        /// </summary>
        public static string ThisArchitectureCannotAutoUpdate {
            get {
                return ResourceManager.GetString("ThisArchitectureCannotAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此功能正在开发中.
        /// </summary>
        public static string ThisFeatureIsCurrentlyUnderDevelopment {
            get {
                return ResourceManager.GetString("ThisFeatureIsCurrentlyUnderDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该功能仅支持Windows10以上，低于此版本系统不保证激活成功.
        /// </summary>
        public static string ThisFeatureOnlySupportsWindows10AndAbove {
            get {
                return ResourceManager.GetString("ThisFeatureOnlySupportsWindows10AndAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该功能仅支持Windows平台.
        /// </summary>
        public static string ThisFeatureOnlySupportsWindowsPlatform {
            get {
                return ResourceManager.GetString("ThisFeatureOnlySupportsWindowsPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组总数量.
        /// </summary>
        public static string TotalNumberOfMod {
            get {
                return ResourceManager.GetString("TotalNumberOfMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 百宝箱.
        /// </summary>
        public static string TreasureBox {
            get {
                return ResourceManager.GetString("TreasureBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法为基岩版添加模组.
        /// </summary>
        public static string UnableToAddModsForBedrockEdition {
            get {
                return ResourceManager.GetString("UnableToAddModsForBedrockEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未处理的异常.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的文件类型.
        /// </summary>
        public static string UnsupportedFileType {
            get {
                return ResourceManager.GetString("UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解压.
        /// </summary>
        public static string Unzip {
            get {
                return ResourceManager.GetString("Unzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在解压整合包.
        /// </summary>
        public static string UnzipingModPack {
            get {
                return ResourceManager.GetString("UnzipingModPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新失败.
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提升至管理员权限.
        /// </summary>
        public static string UpgradeToAdministratorPrivileges {
            get {
                return ResourceManager.GetString("UpgradeToAdministratorPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提升至管理员权限失败.
        /// </summary>
        public static string UpgradeToAdministratorPrivilegesFail {
            get {
                return ResourceManager.GetString("UpgradeToAdministratorPrivilegesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行操作需要提升至管理员权限，点击确定以管理员权限重启程序.
        /// </summary>
        public static string UpgradeToAdministratorPrivilegesTip {
            get {
                return ResourceManager.GetString("UpgradeToAdministratorPrivilegesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用全局设置.
        /// </summary>
        public static string UseGlobalSetting {
            get {
                return ResourceManager.GetString("UseGlobalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户数据文件夹.
        /// </summary>
        public static string UserDataFolder {
            get {
                return ResourceManager.GetString("UserDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证代码.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证服务器.
        /// </summary>
        public static string VerificationServer {
            get {
                return ResourceManager.GetString("VerificationServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在验证账户.
        /// </summary>
        public static string VerifyingAccount {
            get {
                return ResourceManager.GetString("VerifyingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本文件夹.
        /// </summary>
        public static string VersionFolder {
            get {
                return ResourceManager.GetString("VersionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本列表.
        /// </summary>
        public static string VersionList {
            get {
                return ResourceManager.GetString("VersionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本设置.
        /// </summary>
        public static string VersionSetting {
            get {
                return ResourceManager.GetString("VersionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看更新内容.
        /// </summary>
        public static string ViewUpdatedContent {
            get {
                return ResourceManager.GetString("ViewUpdatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待游戏窗口出现.
        /// </summary>
        public static string WaitForGameWindowAppear {
            get {
                return ResourceManager.GetString("WaitForGameWindowAppear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在等待微软账户验证完成
        ///跳转至浏览器完成验证.
        /// </summary>
        public static string WaitForMicrosoftVerification {
            get {
                return ResourceManager.GetString("WaitForMicrosoftVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口标题栏样式.
        /// </summary>
        public static string WindowTitleBarStyle {
            get {
                return ResourceManager.GetString("WindowTitleBarStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱不可为空.
        /// </summary>
        public static string YggdrasilEmailIsEmpty {
            get {
                return ResourceManager.GetString("YggdrasilEmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不可为空.
        /// </summary>
        public static string YggdrasilPasswordIsEmpty {
            get {
                return ResourceManager.GetString("YggdrasilPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证服务器不可为空.
        /// </summary>
        public static string YggdrasilServerUrlIsEmpty {
            get {
                return ResourceManager.GetString("YggdrasilServerUrlIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string zh_CN {
            get {
                return ResourceManager.GetString("zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 繁體中文.
        /// </summary>
        public static string zh_Hant {
            get {
                return ResourceManager.GetString("zh_Hant", resourceCulture);
            }
        }
    }
}
