//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMCL.Main.Public.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YMCL.Main.Public.Langs.MainLang", typeof(MainLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件夹 的本地化字符串。
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中项 的本地化字符串。
        /// </summary>
        public static string DelSeletedItem {
            get {
                return ResourceManager.GetString("DelSeletedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft文件夹 的本地化字符串。
        /// </summary>
        public static string MinecraftFolder {
            get {
                return ResourceManager.GetString("MinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  下载 的本地化字符串。
        /// </summary>
        public static string NavDownload {
            get {
                return ResourceManager.GetString("NavDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  启动 的本地化字符串。
        /// </summary>
        public static string NavLaunch {
            get {
                return ResourceManager.GetString("NavLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  更多 的本地化字符串。
        /// </summary>
        public static string NavMore {
            get {
                return ResourceManager.GetString("NavMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  音乐 的本地化字符串。
        /// </summary>
        public static string NavMusic {
            get {
                return ResourceManager.GetString("NavMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  设置 的本地化字符串。
        /// </summary>
        public static string NavSetting {
            get {
                return ResourceManager.GetString("NavSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需选择&apos;.minecraft&apos;文件夹 的本地化字符串。
        /// </summary>
        public static string NeedToSelectMinecraftFolder {
            get {
                return ResourceManager.GetString("NeedToSelectMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择&apos;.minecraft&apos;文件夹 的本地化字符串。
        /// </summary>
        public static string SelectMinecraftFolder {
            get {
                return ResourceManager.GetString("SelectMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功 的本地化字符串。
        /// </summary>
        public static string SuccessAdd {
            get {
                return ResourceManager.GetString("SuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string SuccessRemove {
            get {
                return ResourceManager.GetString("SuccessRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在此项目 的本地化字符串。
        /// </summary>
        public static string TheItemAlreadyExist {
            get {
                return ResourceManager.GetString("TheItemAlreadyExist", resourceCulture);
            }
        }
    }
}
