name: Publish

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  time:
    runs-on: ubuntu-latest
    outputs:
      v: ${{ steps.date.outputs.time }}
      y: ${{ steps.date.outputs.y }}
      md: ${{ steps.date.outputs.md }}
      hm: ${{ steps.date.outputs.hm }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Time
        id: date
        run: |
          echo "::set-output name=time::$(date +'%Y.%m.%d.%H.%M')"
          echo "::set-output name=y::$(date +'%Y')"
          echo "::set-output name=md::$(date +'%m%d')"
          echo "::set-output name=hm::$(date +'%H%M')"
      - name: EchoTime
        run: |
          echo "The current time is: ${{ steps.date.outputs.time }}"

  linux:
    runs-on: ubuntu-22.04
    needs: time
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Time
        id: date
        run: |
          echo "${{ needs.time.outputs.v }}" > ./YMCL.Main/YMCL/Public/Texts/DateTime.txt
          echo "Version is ${{ needs.time.outputs.v }}"
      - name: Dependency
        run: |
          dotnet tool install -g KuiperZone.PupNet
          sudo apt-get update
          sudo apt-get install fuse
      - name: Build-AppImage
        run: |
          cd ./YMCL.Main/YMCL.Desktop
          sudo su
          pupnet --runtime linux-x64 --kind appimage -o YMCL.Desktop.linux.x64.AppImage -y --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
          pupnet --runtime linux-arm --kind appimage -o YMCL.Desktop.linux.arm.AppImage -y --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
          pupnet --runtime linux-arm64 --kind appimage -o YMCL.Desktop.linux.arm64.AppImage -y --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
      - name: Build-MacOsApp
        run: |
          cd ./YMCL.Main/YMCL.Desktop
          sudo su
          dotnet restore -r osx-x64
          dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64  -property:Configuration=Release -p:SelfContained=true
          cp ./Icon.Border.icns ./bin/Release/net8.0/osx-x64/publish/YMCL.app/Contents/Resources/Icon.Border.icns
          cd ./bin/Release/net8.0/
          cd ./osx-x64/publish/
          zip -9 -r ../../YMCL.Desktop.osx.mac.x64.app.zip ./YMCL.app
      - name: Build-WinExe
        run: |
          cd ./YMCL.Main/YMCL.Desktop
          sudo su
          dotnet publish -r win-x86 --self-contained true -p:PublishSingleFile=true
          dotnet publish -r win-x64 --self-contained true -p:PublishSingleFile=true
          dotnet publish -r win-arm64 --self-contained true -p:PublishSingleFile=true
          mv ./bin/Release/net8.0/win-x86/publish/YMCL.Desktop.exe ./bin/Release/net8.0/win-x86/publish/YMCL.Desktop.win7.x86.exe
          mv ./bin/Release/net8.0/win-x64/publish/YMCL.Desktop.exe ./bin/Release/net8.0/win-x64/publish/YMCL.Desktop.win7.x64.exe
          mv ./bin/Release/net8.0/win-arm64/publish/YMCL.Desktop.exe ./bin/Release/net8.0/win-arm64/publish/YMCL.Desktop.win7.arm64.exe
          cd ./bin/Release/net8.0/
          cd ./win-x86/
          zip -9 -r "../YMCL.Desktop.win7.x86.zip" "./publish"
          cd ../
          cd ./win-x64/
          zip -9 -r "../YMCL.Desktop.win7.x64.zip" "./publish"
          cd ../
          cd ./win-arm64/
          zip -9 -r "../YMCL.Desktop.win7.arm64.zip" "./publish"
      - name: UploadArtifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            YMCL.Main/YMCL.Desktop/Deploy/OUT/*
            YMCL.Main/YMCL.Desktop/bin/Release/net8.0/*.zip

  win:
    runs-on: windows-latest
    needs: time
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Dependency-InnoSetup
        uses: ConorMacBride/install-package@v1
        with:
          choco: innosetup
      - name: Chinesize-InnoSetup
        run: |
          Copy-Item "./YMCL.Main/YMCL/Public/Texts/Default.isl" "C:\Program Files (x86)\Inno Setup 6\Default.isl" -Force
      - name: Dependency-Pupnet
        run: |
          dotnet tool install -g KuiperZone.PupNet
      - name: Time
        id: date
        run: |
          echo "${{ needs.time.outputs.v }}" > ./YMCL.Main/YMCL/Public/Texts/DateTime.txt
          echo "Version is ${{ needs.time.outputs.v }}"
        shell: bash
      - name: Build
        run: |
          cd ./YMCL.Main/YMCL.Desktop
          pupnet -r win-x64 -k setup -y -o YMCL.Desktop.win.x64.installer.exe --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
          pupnet -r win-x86 -k setup -y -o YMCL.Desktop.win.x86.installer.exe --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
          pupnet -r win-arm64 -k setup -y -o YMCL.Desktop.win.arm64.installer.exe --app-version ${{ needs.time.outputs.y }}.${{ needs.time.outputs.md }}.${{ needs.time.outputs.hm }}
      - name: UploadArtifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-artifacts
          path: |
            ./YMCL.Main/YMCL.Desktop/Deploy/OUT/*

  mac:
    needs: [linux, win, time]
    runs-on: macos-latest
    steps:
      - name: Download-LinuxArtifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-artifacts
          path: ./YMCL.Release/
      - name: Unzip
        run: |
          unzip -n ./YMCL.Release/bin/Release/net8.0/YMCL.Desktop.osx.mac.x64.app.zip -d ./app.x64
      - name: Build-MacOsDmg-x64
        uses: L-Super/create-dmg-actions@v1.0.3
        with:
          dmg_name: "YMCL.Desktop.osx.mac.x64"
          src_dir: "./app.x64/YMCL.app"
      - name: UploadArtifacts
        uses: actions/upload-artifact@v4
        with:
          name: osx-artifacts
          path: |
            ./YMCL.Desktop.osx.mac.x64.dmg

  publish:
    needs: [linux, win, mac, time]
    runs-on: ubuntu-latest
    steps:
      - name: Time
        id: gdate
        run: |
          echo "date=$(date +'%Y-%m-%d.%H-%M-%S')" >> $GITHUB_OUTPUT
          echo "title=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_OUTPUT
      - name: Download-LinuxArtifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-artifacts
          path: ./YMCL.Release/
      - name: Download-WindowsArtifacts
        uses: actions/download-artifact@v4
        with:
          name: win-artifacts
          path: ./YMCL.Release/
      - name: Download-MacArtifacts
        uses: actions/download-artifact@v4
        with:
          name: osx-artifacts
          path: ./YMCL.Release/
      - name: List Files
        run: |
          ls -la ./YMCL.Release/
      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          title: "v${{ needs.time.outputs.v }}"
          automatic_release_tag: "AutoPublish-${{ steps.gdate.outputs.date }}"
          prerelease: false
          files: |
            YMCL.Release/*.exe
            YMCL.Release/*.dmg
            YMCL.Release/Deploy/OUT/*.AppImage
            YMCL.Release/bin/Release/net8.0/*.zip
